### ISSUE TITLE
InputStream ist null

### ISSUE THREAD

**Issue by ralf-ueberfuhr-ars** [PoltorakCode/SampleAPISax#1]
Bitte korrigieren

**Comment by ChristopherCz** [comment]
Beim ausführen der Main-Methode: 

java.lang.IllegalArgumentException: InputStream cannot be null
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:193)
	at bookstore/bookstore.buchladenSAX.display(buchladenSAX.java:21)
	at bookstore/bookstore.Main.main(Main.java:14)
